package com.fusionflux.portalcubed.blocks;

import com.google.common.collect.ImmutableMap;
import net.minecraft.world.level.material.MaterialColor;

import java.util.Map;

public class MaterialColorNames {
    public static final Map<String, MaterialColor> COLORS = ImmutableMap.<String, MaterialColor>builder()
        .put("none", MaterialColor.NONE)
        .put("grass", MaterialColor.GRASS)
        .put("sand", MaterialColor.SAND)
        .put("wool", MaterialColor.WOOL)
        .put("fire", MaterialColor.FIRE)
        .put("ice", MaterialColor.ICE)
        .put("metal", MaterialColor.METAL)
        .put("plant", MaterialColor.PLANT)
        .put("snow", MaterialColor.SNOW)
        .put("clay", MaterialColor.CLAY)
        .put("dirt", MaterialColor.DIRT)
        .put("stone", MaterialColor.STONE)
        .put("water", MaterialColor.WATER)
        .put("wood", MaterialColor.WOOD)
        .put("quartz", MaterialColor.QUARTZ)
        .put("color_orange", MaterialColor.COLOR_ORANGE)
        .put("color_magenta", MaterialColor.COLOR_MAGENTA)
        .put("color_light_blue", MaterialColor.COLOR_LIGHT_BLUE)
        .put("color_yellow", MaterialColor.COLOR_YELLOW)
        .put("color_light_green", MaterialColor.COLOR_LIGHT_GREEN)
        .put("color_pink", MaterialColor.COLOR_PINK)
        .put("color_gray", MaterialColor.COLOR_GRAY)
        .put("color_light_gray", MaterialColor.COLOR_LIGHT_GRAY)
        .put("color_cyan", MaterialColor.COLOR_CYAN)
        .put("color_purple", MaterialColor.COLOR_PURPLE)
        .put("color_blue", MaterialColor.COLOR_BLUE)
        .put("color_brown", MaterialColor.COLOR_BROWN)
        .put("color_green", MaterialColor.COLOR_GREEN)
        .put("color_red", MaterialColor.COLOR_RED)
        .put("color_black", MaterialColor.COLOR_BLACK)
        .put("gold", MaterialColor.GOLD)
        .put("diamond", MaterialColor.DIAMOND)
        .put("lapis", MaterialColor.LAPIS)
        .put("emerald", MaterialColor.EMERALD)
        .put("podzol", MaterialColor.PODZOL)
        .put("nether", MaterialColor.NETHER)
        .put("terracotta_white", MaterialColor.TERRACOTTA_WHITE)
        .put("terracotta_orange", MaterialColor.TERRACOTTA_ORANGE)
        .put("terracotta_magenta", MaterialColor.TERRACOTTA_MAGENTA)
        .put("terracotta_light_blue", MaterialColor.TERRACOTTA_LIGHT_BLUE)
        .put("terracotta_yellow", MaterialColor.TERRACOTTA_YELLOW)
        .put("terracotta_light_green", MaterialColor.TERRACOTTA_LIGHT_GREEN)
        .put("terracotta_pink", MaterialColor.TERRACOTTA_PINK)
        .put("terracotta_gray", MaterialColor.TERRACOTTA_GRAY)
        .put("terracotta_light_gray", MaterialColor.TERRACOTTA_LIGHT_GRAY)
        .put("terracotta_cyan", MaterialColor.TERRACOTTA_CYAN)
        .put("terracotta_purple", MaterialColor.TERRACOTTA_PURPLE)
        .put("terracotta_blue", MaterialColor.TERRACOTTA_BLUE)
        .put("terracotta_brown", MaterialColor.TERRACOTTA_BROWN)
        .put("terracotta_green", MaterialColor.TERRACOTTA_GREEN)
        .put("terracotta_red", MaterialColor.TERRACOTTA_RED)
        .put("terracotta_black", MaterialColor.TERRACOTTA_BLACK)
        .put("crimson_nylium", MaterialColor.CRIMSON_NYLIUM)
        .put("crimson_stem", MaterialColor.CRIMSON_STEM)
        .put("crimson_hyphae", MaterialColor.CRIMSON_HYPHAE)
        .put("warped_nylium", MaterialColor.WARPED_NYLIUM)
        .put("warped_stem", MaterialColor.WARPED_STEM)
        .put("warped_hyphae", MaterialColor.WARPED_HYPHAE)
        .put("warped_wart_block", MaterialColor.WARPED_WART_BLOCK)
        .put("deepslate", MaterialColor.DEEPSLATE)
        .put("raw_iron", MaterialColor.RAW_IRON)
        .put("glow_lichen", MaterialColor.GLOW_LICHEN)
        .build();

    private MaterialColorNames() {
    }
}
